<<<<<<< HEAD
const SERVER_IP = 'remarkably-arriving-imp.ngrok-free.app'; 

export const environment = {
    production: true,
    apiLogin: `https://${SERVER_IP}/user/login`,
    apiGetInfo: `https://${SERVER_IP}/user/info`,
    apiGetAtm: `https://${SERVER_IP}/Atm/get`,
    urlSocketCl: `wss://${SERVER_IP}:8082/game/cl`,
    apiGetHistoryGame: `https://${SERVER_IP}/game/getHistoryCl`,
    apiSaveHisPlayer: `https://${SERVER_IP}/game/savePlayerHis`,
    apiSaveHisBalan:`https://${SERVER_IP}/Atm/saveHis`,
    apiupdateBalan:`https://${SERVER_IP}/Atm/updateBalance`,
    apigetListFriend :`https://${SERVER_IP}/friend/getListFriend`,
    apiaddFriend :`https://${SERVER_IP}/friend/addFriend`,
    apiacceptFriend :`https://${SERVER_IP}/friend/acceptFriend`,
    apideleFriend :`https://${SERVER_IP}/friend/deleteFriend`,
    apideleFriendRequets :`https://${SERVER_IP}/friend/deleteFriendRequest`,
    apiGetrequets:`https://${SERVER_IP}/friend/getFriendRequests`,
    keysecret:"anhthanhdz",
    apiSearchAtm: `https://${SERVER_IP}/Atm/search`,
    apiSaveHisBalance: `https://${SERVER_IP}/Atm/saveHis`,
    apiSearchFullname: `https://${SERVER_IP}/user/searchFullname`,
    urlSocketMess: `wss://${SERVER_IP}:8082/mess`,
    apiGetChatHis: `https://${SERVER_IP}/mess/getChatHis`,
    apiFootball:  '/api/competitions/PL/matches',
    keyFootball:'17ee52ab7c3d494794f524ea8abff2f8',
    apigetbetHisfbxs:`https://${SERVER_IP}/betHisfbxs/getbetHisfbxs`,
    apiPlaceBet:`https://${SERVER_IP}/betHisfbxs/placeBet`,
    apiLottery :`https://xoso188.net/api/front/open/lottery/history/list/5/miba`,
    apiGetRelative:` https://${SERVER_IP}/friend/getRelative`,
    apigetHisfbxs:`https://${SERVER_IP}/betHisfbxs/getHisfbXs`,
    apiGetHisBalance:`https://${SERVER_IP}/game/getPlayerHis`,
    apiGetPlayerHisAll:`https://${SERVER_IP}/game/getPlayerHisAll`,
    apiRegister:`https://${SERVER_IP}/regis`,
    apiCreateAtm:`https://${SERVER_IP}/Atm/createATM`,
    apiGetFriendRelative:`https://${SERVER_IP}/friend/getRelativeMy`,

};
=======
const SERVER_IP = '127.0.0.1';

export const environment = {
  production: true,
  apiLogin: `http://${SERVER_IP}:8082/user/login`,
  apiGetInfo: `http://${SERVER_IP}:8082/user/info`,
  apiGetAtm: `http://${SERVER_IP}:8082/Atm/get`,
  urlSocketCl: `ws://${SERVER_IP}:8082/game/cl`,
  apiGetHistoryGame: `http://${SERVER_IP}:8082/game/getHistoryCl`,
  apiSaveHisPlayer: `http://${SERVER_IP}:8082/game/savePlayerHis`,
  apiSaveHisBalan: `http://${SERVER_IP}:8082/Atm/saveHis`,
  apiupdateBalan: `http://${SERVER_IP}:8082/Atm/updateBalance`,
  apigetListFriend: `http://${SERVER_IP}:8082/friend/getListFriend`,
  apiaddFriend: `http://${SERVER_IP}:8082/friend/addFriend`,
  apiacceptFriend: `http://${SERVER_IP}:8082/friend/acceptFriend`,
  apideleFriend: `http://${SERVER_IP}:8082/friend/deleteFriend`,
  apideleFriendRequets: `http://${SERVER_IP}:8082/friend/deleteFriendRequest`,
  apiGetrequets: `http://${SERVER_IP}:8082/friend/getFriendRequests`,
  keysecret: 'anhthanhdz',
  apiSearchAtm: `http://${SERVER_IP}:8082/Atm/search`,
  apiSaveHisBalance: `http://${SERVER_IP}:8082/Atm/saveHis`,
  apiSearchFullname: `http://${SERVER_IP}:8082/user/searchFullname`,
  urlSocketMess: `ws://${SERVER_IP}:8082/mess`,
  apiGetChatHis: `http://${SERVER_IP}:8082/mess/getChatHis`,
  // apiFootball: `/api/competitions/PL/matches`,
  apiFootball: `http://${SERVER_IP}:8082/football/matches`,
  keyFootball: '17ee52ab7c3d494794f524ea8abff2f8',
  apigetbetHisfbxs: `http://${SERVER_IP}:8082/betHisfbxs/getbetHisfbxs`,
  apiPlaceBet: `http://${SERVER_IP}:8082/betHisfbxs/placeBet`,
  apiLottery: `https://xoso188.net/api/front/open/lottery/history/list/5/miba`,
  apiGetRelative: ` http://${SERVER_IP}:8082/friend/getRelative`,
  apigetHisfbxs: `http://${SERVER_IP}:8082/betHisfbxs/getHisfbXs`,
  apiGetHisBalance: `http://${SERVER_IP}:8082/game/getPlayerHis`,
  apiGetPlayerHisAll: `http://${SERVER_IP}:8082/game/getPlayerHisAll`,
  apiRegister: `http://${SERVER_IP}/user/regis`,
  apiCreateAtm: `http://${SERVER_IP}:8082/Atm/createATM`,
  apiGetFriendRelative: `http://${SERVER_IP}:8082/friend/getRelativeMy`,
  apiGetDailyClosingBalance: `http://${SERVER_IP}:8082/Atm/getDailyClosingBalance`,
  apiGetDailyRecharge: `http://${SERVER_IP}:8082/Atm/getDailyRecharge`,
  apiSignUp: `http://${SERVER_IP}:8082/api/v1/auth/signup`,
  apiVerify: `http://${SERVER_IP}:8082/api/v1/auth/verify`,
};
    
>>>>>>> d92f113516b4bd53b68a07a61fe24e281ec48b48
